#VotingAppPod
apiVersion: apps/v1

kind: Deployment

metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
    app: voting-app-usingdep

spec:
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: voting-app-usingpods

    spec:
      containers:
        - name: postgres
          image: postgres:9.4
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name:  POSTGRES_PASSWORD
              value: "postgres"
            - name:  POSTGRES_HOST_AUTH_METHOD
              value: "trust"
          ports:
            - containerPort: 5432
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: voting-app-usingpods

