apiVersion: v1

kind: Service

metadata:
  name: redis
  labels:
    name: redis-service
    app: voting-app-usingdep

spec:
  type: ClusterIP

  ports:
  - targetPort: 6379
    port: 6379

  selector:
    name: redis-deplyment
    app: voting-app-usingdep

